# Generated by Django 2.2 on 2020-12-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_documento', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='doc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionario.Documento'),
        ),
    ]
