# Generated by Django 2.2 on 2020-12-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_auto_20201202_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
