# Generated by Django 2.2 on 2020-12-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='funcionario.Funcionario'),
        ),
    ]
